language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy scipy pytest pytest-cov gdal>=2.2 coverage sphinx
  - source activate test
  - pip install gp_emulator
  - pip install -U codecov
  - pip install coveralls
  - pip install git+https://github.com/jgomezdans/BRDF_descriptors
  - python setup.py install
script:
  - python -m pytest --cov
  - coverage xml
after_success:
  - codecov
  - coveralls
